name: Generate chapter pages
on:
  push:
    branches: [ main, master ]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate markdown wrappers from .txt
        shell: bash
        run: |
          shopt -s nullglob
          mkdir -p chapters
          for f in chapters/ch*.txt; do
            base="$(basename "$f" .txt)"        # e.g., ch3
            num="${base#ch}"                    # e.g., 3
            md="chapters/${base}.md"

            # Simple, safe title. (You can get fancy later by reading the first line.)
            title="Chapter ${num}"

            cat > "$md" <<'EOF'
---
title: PLACEHOLDER_TITLE
order: PLACEHOLDER_ORDER
permalink: /PLACEHOLDER_BASE/
layout: chapter
---

{% capture body %}{% include_relative PLACEHOLDER_BASE.txt %}{% endcapture %}
{{ body | newline_to_br }}
EOF

            # Fill placeholders
            sed -i "s/PLACEHOLDER_TITLE/${title//\//\\/}/" "$md"
            sed -i "s/PLACEHOLDER_ORDER/${num}/" "$md"
            sed -i "s/PLACEHOLDER_BASE/${base}/g" "$md"
          done

      - name: Commit wrappers (if any changes)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add chapters/*.md || true
          git diff --cached --quiet || git commit -m "Auto-generate chapter pages"
          git push
