name: Generate chapter pages
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate markdown wrappers
        run: |
          mkdir -p chapters
          for f in chapters/ch*.txt; do
            [ -e "$f" ] || continue
            base=$(basename "$f" .txt)
            num=${base#ch}
            md="chapters/${base}.md"
            title="Chapter ${num}"
            cat > "$md" <<EOF
---
title: ${title}
order: ${num}
permalink: /${base}/
layout: chapter
---

{% capture body %}{% include_relative ${base}.txt %}{% endcapture %}
{{ body | newline_to_br }}
EOF
          done
      - name: Commit wrappers
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add chapters/*.md || true
          git diff --cached --quiet || git commit -m "Auto-generate chapter pages"
          git push
