# .github/workflows/chapters.yml
name: Generate chapter pages
on:
  push:
    branches: [ main, master ]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate markdown wrappers from .txt
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob

          mkdir -p chapters

          for f in chapters/ch*.txt; do
            base="$(basename "$f" .txt)"      # ch3
            num="${base#ch}"                  # 3
            md="chapters/${base}.md"

            # Optional: title from first non-empty line, else "Chapter N"
            first_line=$(grep -m1 -E '.\S.+' "$f" || true)
            if [[ -n "${first_line:-}" ]]; then
              title="$first_line"
            else
              title="Chapter ${num}"
            fi

            {
              printf -- '---\n'
              printf -- 'title: %s\n' "$title"
              printf -- 'order: %s\n' "$num"
              printf -- 'permalink: /%s/\n' "$base"
              printf -- 'layout: chapter\n'
              printf -- '---\n\n'
              # Liquid tags for Jekyll (shell won't expand these)
              printf -- '{%% capture body %%}{%% include_relative %s.txt %%}{%% endcapture %%}\n' "$base"
              printf -- '{{ body | newline_to_br }}\n'
            } > "$md"
          done

      - name: Commit wrappers (if any changes)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add chapters/*.md || true
          git diff --cached --quiet || git commit -m "Auto-generate chapter pages"
          git push
